version: '3.3'

services:
  bootnode:
    hostname: bootnode
    container_name: bootnode
    environment:
      - BOOTKEY_PATH
    build:
      context: .
      dockerfile: ./Dockerfile
    network_mode: "host"
    ports:
      - 30313
    restart: on-failure
